"""Real dirty ORM state and optional receipt share only the caller transaction."""
from copy import deepcopy
import json
from types import SimpleNamespace

import pytest
from sqlalchemy import Column, Integer, MetaData, String, Table, event, text
from sqlalchemy.orm import Session, registry

from app.services.trading.momentum_neural import held_evaluation_audit as audit
from app.services.trading.momentum_neural import live_runner as lr
from tests.test_exit_verdict_f_state_machine import _le
from tests.test_held_reader_postgres import admitted, market, seed, tick  # noqa: F401


@pytest.mark.parametrize("fault", [None, "walk_timeout", "receipt_insert"])
def test_reader_never_preflushes_dirty_parent_and_parent_rollback_removes_receipt(market, monkeypatch, fault):
    seed(market)
    metadata = MetaData()
    table = Table("caller_state", metadata, Column("id", Integer, primary_key=True), Column("value", String))
    mapper = registry()

    class State:
        pass

    mapper.map_imperatively(State, table)
    with market.engine.begin() as conn:
        metadata.create_all(conn)
        conn.execute(table.insert().values(id=1, value="original"))
        conn.execute(text("CREATE TABLE receipt (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK(id>0), payload jsonb)"))
    emitted, rows_seen = [], []

    def emit(receipt_db, session, name, payload):
        if name != "live_exit_evaluation":
            return None
        emitted.append(deepcopy(payload))
        assert receipt_db is not caller and receipt_db.connection() is caller.connection()
        if fault == "receipt_insert":
            receipt_db.execute(text("INSERT INTO receipt(id,payload) VALUES(-1,'{}')"))
        identifier = receipt_db.execute(text("INSERT INTO receipt(payload) VALUES(CAST(:p AS jsonb)) RETURNING id"),
                                        {"p": json.dumps(payload)}).scalar_one()
        return SimpleNamespace(id=identifier)

    monkeypatch.setattr(lr, "_emit", emit)
    monkeypatch.setattr(lr, "_commit_le", lambda sess, le: setattr(sess, "risk_snapshot_json", deepcopy(le)))
    original_returned = audit.QueryObservation.returned

    def returned(self, rows=None, error=None):
        # Moving only market SQL onto Core must not flush unrelated ORM edits.
        assert existing in caller.dirty and pending in caller.new
        rows_seen.append(self.record["role"])
        original_returned(self, rows=rows, error=error)

    monkeypatch.setattr(audit.QueryObservation, "returned", returned)
    try:
        with admitted(market) as lease, Session(market.engine, autoflush=False) as caller:
            existing = caller.get(State, 1)
            existing.value = "pending exit mutation"
            pending = State()
            pending.id, pending.value = 2, "pending decision"
            caller.add(pending)
            if fault == "walk_timeout":
                def inject(conn, cursor, statement, params, context, many):
                    if "FROM iqfeed_trade_ticks" in statement and "after" in params:
                        return "SELECT pg_sleep(3)", {}
                    return statement, params
                event.listen(lease.slot.connection, "before_cursor_execute", inject, retval=True)
            le = _le()
            result, _ = tick(caller, le)
            assert result["action"] is None
            assert not lease.slot.connection.in_transaction()
            assert rows_seen and existing in caller.dirty and pending in caller.new
            assert caller.execute(text("SELECT value FROM caller_state WHERE id=1")).scalar_one() == "original"
            assert caller.execute(text("SELECT count(*) FROM caller_state WHERE id=2")).scalar_one() == 0
            assert len(emitted) == 1
            if fault == "walk_timeout":
                assert emitted[0]["read_roles"]["walk"]["status"] == "query_error"
            if fault == "receipt_insert":
                assert le["exit_verdict"]["evaluation_audit"]["last_attempt"]["status"] == "receipt_missing"
            else:
                assert caller.execute(text("SELECT count(*) FROM receipt")).scalar_one() == 1
            caller.flush()
            assert caller.execute(text("SELECT value FROM caller_state WHERE id=1")).scalar_one() == "pending exit mutation"
            with market.engine.connect() as independent:
                assert independent.execute(text("SELECT value FROM caller_state WHERE id=1")).scalar_one() == "original"
                assert independent.execute(text("SELECT count(*) FROM receipt")).scalar_one() == 0
            caller.rollback()
            assert "evaluation_audit" not in le["exit_verdict"]
        with market.engine.connect() as independent:
            assert independent.execute(text("SELECT value FROM caller_state WHERE id=1")).scalar_one() == "original"
            assert independent.execute(text("SELECT count(*) FROM caller_state WHERE id=2")).scalar_one() == 0
            assert independent.execute(text("SELECT count(*) FROM receipt")).scalar_one() == 0
    finally:
        mapper.dispose()


def test_mid_epoch_disconnect_never_reconnects_or_retries_roles_on_parent(market, monkeypatch):
    from tests.test_held_reader_postgres import wire
    seed(market)
    emitted = wire(monkeypatch)
    original_returned = audit.QueryObservation.returned
    with admitted(market) as lease, Session(market.engine, autoflush=False) as caller:
        connection = lease.slot.connection
        factory_calls = []
        original_factory = market.manager.factory
        monkeypatch.setattr(market.manager, "factory", lambda: factory_calls.append(1) or original_factory())
        parent_market_queries = []

        def guard(conn, cursor, statement, params, context, many):
            if "FROM iqfeed_trade_ticks" in statement:
                parent_market_queries.append(statement)

        event.listen(caller.connection(), "before_cursor_execute", guard)

        def returned(self, rows=None, error=None):
            original_returned(self, rows=rows, error=error)
            if self.record["role"] == "walk" and error is None:
                connection.invalidate()

        monkeypatch.setattr(audit.QueryObservation, "returned", returned)
        le = _le()
        result, _ = tick(caller, le)
        assert result["action"] is None
        assert connection.invalidated and lease.slot.dbapi.closed
        assert not factory_calls and not parent_market_queries
        assert caller.execute(text("SELECT 42")).scalar_one() == 42
        payload = next(p for name, p in emitted if name == "live_exit_evaluation")
        assert payload["market_snapshot"]["common_snapshot"] is True  # the completed walk only
        assert payload["market_snapshot"]["successful_role_reads"] == 1
        assert payload["read_roles"]["G"]["status"] != "query_success"
        assert payload["read_roles"]["D"]["status"] != "query_success"
