"""Shared vocabulary for fast-path universe rotation status values."""
from __future__ import annotations

UNIVERSE_STATUS_ACTIVE = "active"
UNIVERSE_STATUS_SHADOW = "shadow"
UNIVERSE_STATUS_INACTIVE = "inactive"

UNIVERSE_SUBSCRIBED_STATUSES = (
    UNIVERSE_STATUS_ACTIVE,
    UNIVERSE_STATUS_SHADOW,
)
UNIVERSE_ALL_STATUSES = (
    UNIVERSE_STATUS_ACTIVE,
    UNIVERSE_STATUS_SHADOW,
    UNIVERSE_STATUS_INACTIVE,
)

UNIVERSE_REJECT_VOLUME_BELOW = "volume_below_threshold"
UNIVERSE_REJECT_SPREAD_ABOVE = "spread_above_threshold"
UNIVERSE_REJECT_TOP_OF_BOOK_BELOW = "top_of_book_below_threshold"
UNIVERSE_REJECT_SHADOW_TOP_OF_BOOK_BELOW = "shadow_top_of_book_below_probe"
UNIVERSE_REJECT_RANGE_BELOW = "range_below_threshold"
UNIVERSE_REJECT_TRADES_BELOW = "trades_below_threshold"

UNIVERSE_HARD_DEMOTE_REASONS = (
    UNIVERSE_REJECT_RANGE_BELOW,
    UNIVERSE_REJECT_VOLUME_BELOW,
    UNIVERSE_REJECT_TRADES_BELOW,
    UNIVERSE_REJECT_SHADOW_TOP_OF_BOOK_BELOW,
)

__all__ = [
    "UNIVERSE_STATUS_ACTIVE",
    "UNIVERSE_STATUS_SHADOW",
    "UNIVERSE_STATUS_INACTIVE",
    "UNIVERSE_SUBSCRIBED_STATUSES",
    "UNIVERSE_ALL_STATUSES",
    "UNIVERSE_REJECT_VOLUME_BELOW",
    "UNIVERSE_REJECT_SPREAD_ABOVE",
    "UNIVERSE_REJECT_TOP_OF_BOOK_BELOW",
    "UNIVERSE_REJECT_SHADOW_TOP_OF_BOOK_BELOW",
    "UNIVERSE_REJECT_RANGE_BELOW",
    "UNIVERSE_REJECT_TRADES_BELOW",
    "UNIVERSE_HARD_DEMOTE_REASONS",
]
