"""`brain_batch_jobs.job_type` values for scheduler + scan persistence."""

JOB_CRYPTO_BREAKOUT_SCANNER = "crypto_breakout_scanner"
JOB_STOCK_BREAKOUT_SCANNER = "stock_breakout_scanner"
JOB_MOMENTUM_SCANNER = "momentum_scanner"
JOB_PATTERN_IMMINENT_SCANNER = "pattern_imminent_scanner"
JOB_SCHEDULER_WORKER_HEARTBEAT = "scheduler_worker_heartbeat"
JOB_MOMENTUM_LIVE_LOOP_HEARTBEAT = "momentum_live_loop_heartbeat"
JOB_IQFEED_EXACT_PRINT_HEARTBEAT = "iqfeed_exact_print_heartbeat"
IQFEED_EXACT_PRINT_HEARTBEAT_SCHEMA = "iqfeed_exact_print_heartbeat_v1"
IQFEED_EXACT_PRINT_HEARTBEAT_SCOPE = "committed_exact_print_release"
JOB_BRAIN_MARKET_SNAPSHOTS = "brain_market_snapshots"
