"""SQLAlchemy models. Re-export all for backward compatibility: from app.models import User, Chore, ..."""

from .core import BrainWorkerControl, BrokerCredential, Device, PairCode, User
from .projects import Project, ProjectFile
from .chat import ChatLog, ChatMessage, Conversation
from .household import ActivityLog, Birthday, Chore, HousemateProfile, UserMemory, UserStatus
from .intercom import IntercomConsent, IntercomMessage
from .planner import (
    PlanLabel,
    PlanProject,
    PlanTask,
    ProjectMember,
    TaskActivity,
    TaskComment,
    TaskLabel,
    TaskWatcher,
)
from .coding_task import (
    CodingAgentSuggestion,
    CodingAgentSuggestionApply,
    CodingBlockerReport,
    CodingTaskBrief,
    CodingTaskValidationRun,
    CodingValidationArtifact,
    PlanTaskCodingProfile,
    TaskClarification,
)
from .marketplace import MarketplaceModule
from .trading import (
    BacktestResult,
    BrainBatchJob,
    BreakoutAlert,
    JournalEntry,
    LearningCycleAiReport,
    LearningEvent,
    MarketSnapshot,
    PatternEvidenceHypothesis,
    PatternTradeRow,
    PrescreenCandidate,
    PrescreenSnapshot,
    ScanResult,
    ScanPattern,
    Trade,
    TradingHypothesis,
    TradingInsight,
    TradingInsightEvidence,
    WatchlistItem,
)
from .code_brain import (
    CodeDepAlert,
    CodeDependency,
    CodeHotspot,
    CodeInsight,
    CodeLearningEvent,
    CodeQualitySnapshot,
    CodeRepo,
    CodeReview,
    CodeSearchEntry,
    CodeSnapshot,
)
from .reasoning_brain import (
    ReasoningAnticipation,
    ReasoningConfidenceSnapshot,
    ReasoningEvent,
    ReasoningHypothesis,
    ReasoningInterest,
    ReasoningLearningGoal,
    ReasoningResearch,
    ReasoningUserModel,
)
from .project_brain import (
    AgentEvolution,
    AgentFinding,
    AgentGoal,
    AgentMessage,
    AgentResearch,
    POQuestion,
    PORequirement,
    ProjectAgentState,
)
from .trading_brain_phase1 import (
    BrainCycleLease,
    BrainIntegrationEvent,
    BrainLearningCycleRun,
    BrainPredictionLine,
    BrainPredictionSnapshot,
    BrainStageJob,
)

__all__ = [
    "User",
    "Device",
    "PairCode",
    "BrokerCredential",
    "BrainWorkerControl",
    "Project",
    "ProjectFile",
    "ChatLog",
    "Conversation",
    "ChatMessage",
    "Chore",
    "Birthday",
    "ActivityLog",
    "HousemateProfile",
    "UserMemory",
    "UserStatus",
    "IntercomMessage",
    "IntercomConsent",
    "PlanProject",
    "PlanTask",
    "ProjectMember",
    "TaskComment",
    "TaskActivity",
    "PlanLabel",
    "TaskLabel",
    "TaskWatcher",
    "PlanTaskCodingProfile",
    "TaskClarification",
    "CodingTaskBrief",
    "CodingTaskValidationRun",
    "CodingValidationArtifact",
    "CodingAgentSuggestion",
    "CodingAgentSuggestionApply",
    "CodingBlockerReport",
    "MarketplaceModule",
    "WatchlistItem",
    "Trade",
    "JournalEntry",
    "TradingInsight",
    "TradingInsightEvidence",
    "ScanPattern",
    "PatternTradeRow",
    "PatternEvidenceHypothesis",
    "ScanResult",
    "BacktestResult",
    "MarketSnapshot",
    "LearningCycleAiReport",
    "LearningEvent",
    "TradingHypothesis",
    "PrescreenSnapshot",
    "PrescreenCandidate",
    "BrainBatchJob",
    "CodeRepo",
    "CodeInsight",
    "CodeSnapshot",
    "CodeHotspot",
    "CodeLearningEvent",
    "CodeDependency",
    "CodeQualitySnapshot",
    "CodeReview",
    "CodeDepAlert",
    "CodeSearchEntry",
    "ReasoningUserModel",
    "ReasoningInterest",
    "ReasoningResearch",
    "ReasoningAnticipation",
    "ReasoningEvent",
    "ReasoningLearningGoal",
    "ReasoningHypothesis",
    "ReasoningConfidenceSnapshot",
    "ProjectAgentState",
    "AgentFinding",
    "AgentResearch",
    "AgentGoal",
    "AgentEvolution",
    "AgentMessage",
    "POQuestion",
    "PORequirement",
    "BrainLearningCycleRun",
    "BrainStageJob",
    "BrainCycleLease",
    "BrainIntegrationEvent",
    "BrainPredictionSnapshot",
    "BrainPredictionLine",
]

